#!/bin/bash

echo "---> Config circusd ..."
envtpl /etc/supervisor/conf.d/shinken-arbiter.conf.tpl --keep-template --allow-missing
envtpl /etc/supervisor/conf.d/shinken-broker.conf.tpl --keep-template --allow-missing
envtpl /etc/supervisor/conf.d/shinken-poller.conf.tpl --keep-template --allow-missing
envtpl /etc/supervisor/conf.d/shinken-reactionner.conf.tpl --keep-template --allow-missing
envtpl /etc/supervisor/conf.d/shinken-receiver.conf.tpl --keep-template --allow-missing
envtpl /etc/supervisor/conf.d/shinken-scheduler.conf.tpl --keep-template --allow-missing